name: Build

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Update dependency
        run: |
          go mod tidy
          go install github.com/rhine-tech/scene/cmd/scene@latest

      - name: Build executable
        run: |
          scene build --static app/ayaudiobot --out infoserver-static
          scene build app/ayaudiobot --out infoserver

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-build
          path: |
            dist/infoserver-static
            dist/infoserver